export const CarsActionTypes = {
	FETCH_CARS_START: 'FETCH_CARS_START',
	FETCH_CARS_FAILURE: 'FETCH_CARS_FAILURE',
	FETCH_CARS_SUCCESS: 'FETCH_CARS_SUCCESS',
	SORT_BY_TYPE: 'SORT_BY_TYPE',
	FILTER_BY_INPUT_TEXT: 'FILTER_BY_INPUT_TEXT',
};


